#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts configures the default webpage served to be "Hello World!"
#  Also redirects user to youtube
#
sudo apt-get update -y

#install nginx
sudo apt-get install nginx -y

# create index.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/@sammykingx;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "48i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
