#!/usr/bin/env bash
# Bash script that configures a server to listen to port 80 link sites-avalable to sites-enabled
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
