#!/usr/bin/env bash
# FizzBuzz project
i=1
while [ $i -ne 101 ]
do
	if [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo $i
	fi
	((i++))
	
done
