#!/usr/bin/env bash
# Script that prints "Best School" 10 times but on the 9th it displays "Hi"

counter=0

while ((counter < 10))
do
	echo "Best School"
	((counter++))
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
done
