#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

hours=0
mins=1

while [ $hours -ne 13 ]
do
	echo "Hour: $hours"
	((hours++))
	while [ $mins -ne 60 ]
	do
		echo $mins
		((mins++))
	 done
	 ((mins = 1))
	done
