#!/usr/bin/env bash
# Modifies localhost and facebook.com ip addresses
#sudo cp /etc/hosts etc/hosts.backup

sudo echo "127.0.0.2	localhost" >> /etc/hosts
sudo echo "8.8.8.8	facebook.com" >> /etc/hosts
